// define a variable to import the <Verifier> or <renamedVerifier> solidity contract generated by Zokrates
const SquareVerifier = artifacts.require('Verifier');
const Proof = require('../../zokrates/code/square/proof.json');

// Test verification with correct proof
contract('TestSquareVerifier', accounts => {

    describe('zK-SNARKS validation', function () {
        beforeEach(async () => {
            this.contract = await SquareVerifier.new();
        });

        // - use the contents from proof.json generated from zokrates steps
        it('validates correct proof', async () => {
            let verified = await this.contract.verifyTx(Proof.proof, Proof.inputs)
            assert.equal(verified, true);
        })

        // Test verification with incorrect proof
        it('validates incorrect proof', async () => {
            let verified = await this.contract.verifyTx(Proof.proof, [1, 2]);
            assert.equal(verified, false);
        })
    })
});